"""
Constants and mappings used throughout the application.
"""

# City to airport code mapping
CITY_TO_AIRPORT = {
    "new york": "JFK",
    "nyc": "JFK",
    "los angeles": "LAX",
    "la": "LAX",
    "london": "LHR",
    "paris": "CDG",
    "tokyo": "NRT",
    "berlin": "BER",
    "amsterdam": "AMS",
    "rome": "FCO",
    "barcelona": "BCN",
    "madrid": "MAD",
    "vienna": "VIE",
    "prague": "PRG",
    "budapest": "BUD",
    "warsaw": "WAW",
    "stockholm": "ARN",
    "copenhagen": "CPH",
    "oslo": "OSL",
    "helsinki": "HEL",
    "dublin": "DUB",
    "edinburgh": "EDI",
    "manchester": "MAN",
    "birmingham": "BHX",
    "glasgow": "GLA",
    "dubai": "DXB",
    "abu dhabi": "AUH",
    "sharjah": "SHJ",
    "moscow": "SVO",
    "saint petersburg": "LED",
    "miami": "MIA",
    "chicago": "ORD",
    "san francisco": "SFO",
    "seattle": "SEA",
    "boston": "BOS",
    "washington": "IAD",
    "atlanta": "ATL",
    "denver": "DEN",
    "las vegas": "LAS",
    "orlando": "MCO",
    "houston": "IAH",
    "phoenix": "PHX",
    "salt lake city": "SLC",
    "portland": "PDX",
    "austin": "AUS",
    "nashville": "BNA",
    "charlotte": "CLT",
    "raleigh": "RDU",
    "pittsburgh": "PIT",
    "cleveland": "CLE",
    "cincinnati": "CVG",
    "indianapolis": "IND",
    "columbus": "CMH",
    "detroit": "DTW",
    "milwaukee": "MKE",
    "minneapolis": "MSP",
    "kansas city": "MCI",
    "omaha": "OMA",
    "wichita": "ICT",
    "oklahoma city": "OKC",
    "tulsa": "TUL",
    "albuquerque": "ABQ",
    "el paso": "ELP",
    "san antonio": "SAT",
    "corpus christi": "CRP",
    "lubbock": "LBB",
    "wichita falls": "SPS",
    "amarillo": "AMA",
    "odessa": "MAF",
    "midland": "MAF",
    "san angelo": "SJT",
    "abilene": "ABI",
    "tyler": "TYR",
    "longview": "GGG",
    "texarkana": "TXK",
    "shreveport": "SHV",
    "baton rouge": "BTR",
    "new orleans": "MSY",
    "jackson": "JAN",
    "biloxi": "GPT",
    "mobile": "MOB",
    "pensacola": "PNS",
    "tallahassee": "TLH",
    "savannah": "SAV",
    "charleston": "CHS",
    "myrtle beach": "MYR",
    "wilmington": "ILM",
    "greensboro": "GSO",
    "winston salem": "INT",
    "fayetteville": "FAY",
    "asheville": "AVL",
    "huntsville": "HSV",
    "birmingham al": "BHM",
    "montgomery": "MGM",
    "tucson": "TUS",
    "yuma": "NYL",
    "flagstaff": "FLG",
    "grand canyon": "GCN",
    "page": "PGA",
    "kingman": "IGM",
    "lake havasu city": "HII",
    "bullhead city": "IFP",
    "prescott": "PRC",
    "show low": "SOW",
    "farmington": "FMN",
    "durango": "DRO",
    "cortez": "CEZ",
    "montrose": "MTJ",
    "grand junction": "GJT",
    "glenwood springs": "GWS",
    "aspen": "ASE",
    "vail": "EGE",
    "breckenridge": "QKB",
    "steamboat springs": "HDN",
    "fort collins": "FNL",
    "greeley": "GXY",
    "pueblo": "PUB",
    "colorado springs": "COS",
    "santa fe": "SAF",
    "roswell": "ROW",
    "carlsbad": "CNM",
    "hobbs": "HOB",
    "clovis": "CVN",
    "portales": "PRZ",
    "silver city": "SVC",
    "deming": "DMN",
    "las cruces": "LRU",
    "truth or consequences": "TCS",
    "socorro": "ONM",
    "gallup": "GUP",
    "zuni pueblo": "ZUN",
    "window rock": "RQE",
    "chinle": "E91",
    "crownpoint": "0E8",
    "shiprock": "5V5",
    "casper": "CPR",
    "cheyenne": "CYS",
    "laramie": "LAR",
    "rawlins": "RWL",
    "rock springs": "RKS",
    "evanston": "EVW",
    "heber city": "W103",
    "park city": "W104",
    "midway": "W105",
    "kamas": "W106",
    "roosevelt": "W107",
    "duchesne": "W108",
    "altamont": "W109",
    "tabiona": "W110",
    "fruitland": "W111",
    "neola": "W112",
    "lapoint": "W113",
    "jensen": "W114",
    "vernal": "W115",
    "dutch john": "W116",
    "manila": "W117",
    "cedar city": "CDC",
    "bryce canyon": "BCE",
    "valle": "VLE",
    "taylor": "TYZ",
    "holbrook": "HBK",
    "grants": "GNT",
    "los alamos": "LAM",
    "los lunas": "LUA",
    "double eagle ii": "AEG",
    "conchas lake": "CNX",
    "newkirk": "W148",
    "ponca city": "PNC",
    "blackwell": "BWL",
    "pawhuska": "H76",
    "bartlesville": "BVO",
    "nowata": "H66",
    "coffeeyville": "CFV",
    "independence": "IDP",
    "parsons": "PPF",
    "chanute": "CNU",
    "fort scott": "FSK",
    "garnett": "K68",
    "osage city": "53K",
    "ottawa": "OWI",
    "wellsville": "K68",
    "lawrence": "LWC",
    "topeka": "FOE",
    "gardner": "K34",
    "new century": "JCI",
    "johnson county": "OJC",
    "olathe": "JCI",
    "bonner springs": "W149",
    "de soto": "W150",
    "eudora": "W151",
    "lincolnville": "W152",
    "mc louth": "W153",
    "osawatomie": "W154",
    "paola": "W155",
    "tonganoxie": "W156",
    "troy": "W157",
    "wathena": "W158",
    "weston": "W159",
    "winchester": "W160",
    "basehor": "W161",
    "bendena": "W162",
    "denison": "W163",
    "effingham": "W164",
    "everest": "W165",
    "fairfax": "W166",
    "fanning": "W167",
    "graham": "W168",
    "haden": "W169",
    "helena": "W170",
    "holton": "W171",
    "horton": "W172",
    "lancaster": "W173",
    "leona": "W174",
    "mayetta": "W175",
    "melvern": "W176",
    "netawaka": "W177",
    "norcatur": "W178",
    "onaga": "W179",
    "overbrook": "W180",
    "powhattan": "W181",
    "quenemo": "W182",
    "reserve": "W183",
    "rossville": "W184",
    "sabetha": "W185",
    "seneca": "W186",
    "silver lake": "W187",
    "soldier": "W188",
    "talmage": "W189",
    "verona": "W190",
    "volkland": "W191",
    "wakarusa": "W192",
    "wetmore": "W193",
    "whiting": "W194",
    "williamsburg": "W195",
    "auburn": "W196",
    "burlingame": "W197",
    "bushong": "W198",
    "carbondale": "W199",
    "cassoday": "W200",
    "cedar point": "W201",
    "council grove": "W202",
    "dwight": "W203",
    "emmett": "W204",
    "florence": "W205"
}


